version: 2
jobs:
  test:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: unicef/etools:test-base
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          DJANGO_SETTINGS_MODULE: EquiTrack.settings.production
          TEST_SETTINGS: EquiTrack.settings.production

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "EquiTrack/requirements/base.txt" }}
      - run:
          command: |
            virtualenv env1
            . env1/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "EquiTrack/requirements/base.txt" }}
          paths:
            - "env1"
      - run:
          command: |
            . env1/bin/activate
            cd EquiTrack
            bash runtests.sh;
      - store_artifacts:
          path: test-reports/
          destination: tr1

  build_and_deploy:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: unicef/etools:test-base
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Building the image
          command: |
            TAG=${CIRCLE_BRANCH}
            docker build -t unicef/etools:$TAG .
            docker run -it -e "DATABASE_URL=postgis://root@localhost:5432/circle_test" -e SECRET_KEY unicef/etools:$TAG bash runtests.sh
#      - run:
#          name: Pushing to Docker Hub
#          command: |
#            docker login -u $DOCKER_USER -p $DOCKER_PASS
#            docker push unicef/etools:$TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - staging
                - develop
                - prp-refactoring
                - ci-updates