version: 2
jobs:
  test:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: unicef/etools:test-base-p3-v2
        environment:
          PGHOST: 127.0.0.1
          DATABASE_URL: "postgis://postgres:postgres@localhost:5432/circle_test"
      - image: circleci/postgres:9.5-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          PGUSER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
      - image: redis
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}--{{ checksum "Pipfile.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Requirements
          command: pipenv install -d --ignore-pipfile
      - run:
          name: Run Tests
          command: |
            tox -re d20,report
      - save_cache:
          key: deps2-{{ .Branch }}--{{ checksum "src/requirements/test.txt" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "env1"
            - /root/.cache/pip
      - store_artifacts:
          path: build/coverage
          destination: coverage

  build_and_deploy:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: unicef/etools:test-base-p3-v2
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Building the image
          command: |
            TAG=${CIRCLE_BRANCH}
            docker build -t unicef/etools:$TAG .
      - run:
          name: Pushing to Docker Hub
          command: |
            TAG=${CIRCLE_BRANCH}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push unicef/etools:$TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - staging
                - develop
                - prp-refactoring
                - ci-updates
