version: 2
jobs:
  test:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: unicef/etools:test-base-p37-v3
        environment:
          PGHOST: 127.0.0.1
          DATABASE_URL: "postgis://postgres:postgres@localhost:5432/circle_test"
      - image: circleci/postgres:9.5-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          PGUSER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
      - image: redis
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}--{{ checksum "Pipfile.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Tests
          command: |
            pip install tox
            tox -e d22,report
      - save_cache:
          key: deps2-{{ .Branch }}--{{ checksum "Pipfile.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "env1"
            - /root/.cache/pip
      - store_artifacts:
          path: build/coverage
          destination: coverage

  build_and_deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Building the image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            BASE_TAG=$(md5sum Pipfile.lock | cut -c1-10)
            TAG=${CIRCLE_BRANCH}
            (docker pull unicef/etools-base:$BASE_TAG) ||
            (docker build -t unicef/etools-base:$BASE_TAG -f Dockerfile-base . && docker push unicef/etools-base:$BASE_TAG)
            docker build -t unicef/etools:$TAG .
      - run:
          name: Pushing to Docker Hub
          command: |
            TAG=${CIRCLE_BRANCH}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push unicef/etools:$TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy
